prisma/graphqlgen

package.json, src/generators/ts-scaffolder.ts, src/tests/scaffold-typescript/__snapshots__/basic.test.ts.snap, src/tests/scaffold-typescript/__snapshots__/large-schema.test.ts.snap
Fixes https://github.com/prisma/graphql-resolver-codegen/issues/25
=> fix(interface types): use ? in place of | null

src/tests/fixtures/scalar.graphql, src/tests/scaffold-typescript/__snapshots__/basic.test.ts.snap, src/tests/scaffold-typescript/basic.test.ts, src/tests/typescript/__snapshots__/basic.test.ts.snap, src/tests/typescript/basic.test.ts
Validates that https://github.com/prisma/graphql-resolver-codegen/issues/30 is resolved in `0.1.6`.
=> fix(test): add test for custom scalar Json

src/generators/ts-generator.ts, src/tests/typescript/__snapshots__/basic.test.ts.snap, src/tests/typescript/__snapshots__/large-schema.test.ts.snap
=> Added do not edit comment on top of gen file

package.json, src/generators/flow-generator.ts, src/generators/flow-scaffolder.ts, src/generators/ts-scaffolder.ts, src/tests/flow/__snapshots__/basic.test.ts.snap, src/tests/flow/__snapshots__/large-schema.test.ts.snap, src/tests/flow/basic.test.ts, src/tests/flow/large-schema.test.ts, src/tests/scaffold-flow/__snapshots__/basic.test.ts.snap, src/tests/scaffold-flow/__snapshots__/large-schema.test.ts.snap, src/tests/scaffold-typescript/__snapshots__/basic.test.ts.snap, src/tests/scaffold-typescript/__snapshots__/large-schema.test.ts.snap
This is released in `0.3.0 @ beta`
=> fix(flow): import type properly and add Promise to resover returns

src/generators/ts-generator.ts, src/tests/fixtures/enum.graphql, src/tests/flow/__snapshots__/basic.test.ts.snap, src/tests/flow/__snapshots__/large-schema.test.ts.snap, src/tests/reason/__snapshots__/basic.test.ts.snap, src/tests/scaffold-flow/__snapshots__/basic.test.ts.snap, src/tests/scaffold-flow/basic.test.ts, src/tests/scaffold-typescript/__snapshots__/basic.test.ts.snap, src/tests/scaffold-typescript/basic.test.ts, src/tests/typescript/__snapshots__/basic.test.ts.snap, src/tests/typescript/__snapshots__/large-schema.test.ts.snap
Fixes https://github.com/prisma/graphql-resolver-codegen/issues/53
Inspired by https://github.com/prisma/graphql-resolver-codegen/pull/55
=> fix(ts): enum input type

packages/graphqlgen/src/generators/ts-generator.ts
Heavily inspired by https://github.com/prisma/graphqlgen/pull/65
Fixes https://github.com/prisma/graphqlgen/issues/64
Todo:
=> fix(input): error on multiple input arguments

packages/graphqlgen/src/ast.ts, packages/graphqlgen/src/generators/ts-generator.ts, packages/graphqlgen/src/generators/ts-scaffolder.ts, packages/graphqlgen/src/index.ts, packages/graphqlgen/src/source-helper.ts, packages/graphqlgen/src/tests/scaffold-typescript/basic.test.ts, packages/graphqlgen/src/validation.ts
=> [WIP] Fix scaffolding scalar resolvers

packages/graphqlgen/src/tests/validation/index.test.ts, packages/graphqlgen/src/validation.ts
- Improved error messages when validating context
- Refactored validation.ts file (mostly re-ordered functions for consistency)
- Added tests for `validateDefinition` function
=> [RFR] Improved context validation and added tests

packages/graphqlgen/src/index.ts, packages/graphqlgen/src/parse.ts
=> [RFR] Implements --init and --version CLI options

README.md
Changed `Popssible` to `Popsible`
=> Updated README - fixed typo

packages/graphqlgen-json-schema/src/definition.ts, packages/graphqlgen-json-schema/src/schema.json, packages/graphqlgen-templates/yoga/graphqlgen.yml, packages/graphqlgen-templates/yoga/src/generated/graphqlgen.ts, packages/graphqlgen/src/ast.ts, packages/graphqlgen/src/generators/ts-generator.ts, packages/graphqlgen/src/generators/ts-scaffolder.ts, packages/graphqlgen/src/index.ts, packages/graphqlgen/src/output.ts, packages/graphqlgen/src/parse.ts, packages/graphqlgen/src/source-helper.ts, packages/graphqlgen/src/tests/fixtures/union/types.ts, packages/graphqlgen/src/tests/scaffold-typescript/basic.test.ts, packages/graphqlgen/src/validation.ts
=> [RFR] Better models configuration/workflow

packages/graphqlgen-templates/typescript-yoga/src/generated/tmp-resolvers/Mutation.ts, packages/graphqlgen-templates/typescript-yoga/src/generated/tmp-resolvers/Post.ts, packages/graphqlgen-templates/typescript-yoga/src/generated/tmp-resolvers/Query.ts, packages/graphqlgen-templates/typescript-yoga/src/generated/tmp-resolvers/User.ts, packages/graphqlgen/src/generators/common.ts, packages/graphqlgen/src/generators/flow-scaffolder.ts, packages/graphqlgen/src/generators/ts-scaffolder.ts, packages/graphqlgen/src/tests/typescript/__snapshots__/basic.test.ts.snap, packages/graphqlgen/src/tests/typescript/__snapshots__/large-schema.test.ts.snap
=> [RFR] Always render resolver args, and always throw in un-implemented resolvers

packages/graphqlgen/src/glob.ts, packages/graphqlgen/src/tests/glob/extract-glob-pattern.test.ts, packages/graphqlgen/src/tests/glob/handle-glob-pattern.test.ts, packages/graphqlgen/src/tests/path-helpers/index.test.ts, packages/graphqlgen/src/utils.ts
Fixes #179 and fixed globbing at the same time
=> [RFR] Fix path resolution

packages/graphqlgen/src/output.ts, packages/graphqlgen/src/source-helper.ts
- Suggested models from CLI outputs only scalar fields
- Added DateTime as scalar type
Fixes #240
=> [RFR] Suggested models from CLI outputs only scalar fields

CONTRIBUTING.md, README.md
Add a design principles section.
Not really sure if the words are well chosen
=> [RFR] Add CONTRIBUTING.md (with design principles)

packages/graphqlgen/src/generators/common.ts, packages/graphqlgen/src/generators/ts-generator.ts, packages/graphqlgen/src/source-helper.ts, packages/graphqlgen/src/tests/fixtures/input/schema.graphql, packages/graphqlgen/src/tests/fixtures/input/types.ts, packages/graphqlgen/src/tests/typescript/__snapshots__/basic.test.ts.snap, packages/graphqlgen/src/tests/typescript/basic.test.ts
=> feat: graphql schema argument-defaults remove ts/flow arg nullability

.prettierignore, package.json, packages/create-graphqlgen/package.json, packages/create-graphqlgen/prettier.config.js, packages/create-graphqlgen/src/index.ts, yarn.lock
Will close #326
* husky + pretty-quick for painless pre-commit
* prettier fix script for just in case
* prettier installed at workspaces root as that seemed to make most sense
Note:
* running the prettier fix script results in around 24+ file changes. I will make this its own PR for easier reviewing.
* One other point from #326, [prettierci](https://www.prettierci.com), @timsuchanek said he would take care of that.
=> chore: improve prettier usage

packages/graphqlgen/src/generators/common.ts, packages/graphqlgen/src/utils.ts
* minor style changes
* doc
* readability
* type safety
=> refactor: improve utils module

packages/create-graphqlgen/src/index.ts
=> fix: user can select template from create-graphqlgen prompt

docs/01-configuration.md, packages/graphqlgen/src/generators/typescript/generator.ts, packages/graphqlgen/src/index.ts, packages/graphqlgen/src/types.ts, packages/graphqlgen/tests/typescript/__snapshots__/basic.test.ts.snap, packages/graphqlgen/tests/typescript/__snapshots__/large-schema.test.ts.snap, packages/graphqlgen/tests/typescript/basic.test.ts
=> Add configuration property for enabling delegated parent resolvers
